#creation of the pipeline

name: Test hello git

on: 
  - push

jobs:
  MyBuild:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: print
        run: echo "you did it"