name: 'Test hello git'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/@v2
      - name: go
        run: echo "you did it"

      - name: main
        run: python ../../main.py