name: Test hello git
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: print
        run: echo "you did it"
      # - name: main
      #   run: python ../main.py